{% set name = "lume-epics" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 995ad1c337a2e2579aca5cfbfa4c373e19e5e846b9a3f7fa799959d8d0069948

build:
  noarch: python
  number: 0
  entry_points:
    - render-from-template = lume_epics.commands.render_from_template:serve_from_template
    - serve-from-template = lume_epics.commands.serve_from_template:serve_from_template
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - epics-base
    - pyepics
    - pcaspy
    - p4p
    - numpy
    - bokeh
    - click
    - lume-model >=0.8
    - nose >=1.1.2

test:
  imports:
    - lume_epics
  requires:
    - pytest

about:
  home: https://github.com/slaclab/lume-epics
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-epics is a dedicated API for serving LUME model variables with EPICS.
  doc_url: https://slaclab.github.io/lume-epics/
  dev_url: https://github.com/slaclab/lume-epics

extra:
  recipe-maintainers:
    - jacquelinegarrahan
    - ChristopherMayes
